version: '2'

# 2 services, one for drupal, one for postgres

services:
  drupal:
    image: drupal:8.4.2-apache
    ports:
      - '8080:80'
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always

  postgres:
    image: postgres:10.1
    environment:
      - POSTGRES_PASSWORD=example
    restart: always